language: java
sudo: true
jdk: oraclejdk8
script: env && ./mvnw package -B
before_install:
- chmod +x mvnw
install:
- mvn -N io.takari:maven:wrapper
- "./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
deploy:
  provider: cloudfoundry
  username: diego126.tn@gmail.com
  password:
    secure: BwV7ApKH+ikl9dGVmmEHLcGv9/jmi0xiLuu0GPqGuPUn1Z4sIQCdYW2nLwE0no00iQh/GRMSlGgLUCrHsmhZsIz1gLERaQV/PONbwBSJCNU2U2wGXTrUGZ74CyqYCj5amqIJKZ6hWkYAgmYWiCZcSyNyxav9SBylPF76puJ8RDdrf/kmlYWoq
LBGQEL9lC6KMzt108oDJ0qIRGlA1nbVvvYmyg7jbiMakalX05RZSWGaG/23ODTIG5nnetfwe8ZML5V+bLwJPiZoW+jde6pMZNpt503nFT5siBSI8znUSnZyDPR7Bn8P1htN3h5+eq+abx1nP2pqyFcJl7DtfTYN7pRFjmu3Ako30DMuvv5/mjcFs/hamPVNr
mAcvd1yDSLKzeiCZCJ4BQlrn0arrxMQ8FBpWp2ezDqDUE4ziu5OISmPnPAkhK2tOlAxd0GTmwijod6n5Qh6dslKclLXsTbvZO/sl2GxfwRqZk6AotJ2dGQWyhAB6cPI42/pJDzgOyS/qvCHPba8+3Li1TKrt25NJWT2Wflwgjt91Qr2GpS83ZjSvIGwL+Kw4
6UVg2tAdKJYUwnPERKnag1ZM+Ai9zKyfdmKPdugdCQ+32gwKXz1pHf319DfAkjMtO3REU4Hk0RiYV5UwAdPaSa5yMQqZs+vQklqQi+UcsLmgrRwePMMtCI=
  api: https://api.run.pivotal.io
  organization: maestria-fisi
  space: production